# Generated by Django 4.2.7 on 2023-11-15 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_alter_comment_author_id_alter_recipe_author_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_cook',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
