# Generated by Django 4.2.7 on 2023-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0003_rename_author_id_recipe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_cook',
            field=models.CharField(default='', max_length=50),
        ),
    ]
