# Generated by Django 4.2.7 on 2023-11-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0007_remove_recipe_ingredients_remove_recipe_steps_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recept',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='recept',
            new_name='recipe',
        ),
    ]
